### ISSUE TITLE
[BUG] /skull 指令获得的头颅存在异常

### ISSUE THREAD

**Issue by WUGqnwvMQPzl** [TurnALive/TurnALive-IssueTracker#10]
**简要描述你遇到的问题**
通过 `/skull` 指令获得到的玩家头颅，在物品状态下以默认 Steve 或 Alex 的皮肤显示（即使是自己的头颅也是如此），尝试放置时会出现小卡顿，之后显示正常，但是在破坏这些头颅之后，它的物品形态又以默认皮肤显示而非玩家的自定义皮肤。

放置之后的这些异常头颅可能是造成玩家进入某个区域时出现卡顿的诱因之一，在偏僻地方放置若干异常头颅离开后再返回会出现卡顿状况。

在创造服中，放置这些异常的头颅后可以对头颅方块使用 Ctrl+中键 来获得正常的玩家头颅，物品会显示玩家的自定义皮肤。

**复现方法**
1. 使用 `/skull` 获得头颅
2. 服务器在卡顿一段时间后给你一个显示默认皮肤的异常头颅
3. 放置该头颅时客户端会出现一秒左右的卡顿，之后头颅方块显示正常
4. 放置若干个异常头颅后，离开相关区域再返回便会出现明显卡顿状况

**原本预期的行为**
获取到的头颅在物品栏内可以正常显示，并且放置不会出现客户端卡顿状况

**截图**
![Screenshot_20210715_210530](https://user-images.githubusercontent.com/36147447/125793012-5c452d62-1366-480e-8fa1-4d3f31565b37.png)

**发现日期**
不明确...可能这个问题在前几天就已经出现？

**是否使用基岩版登录**
否

**Comment by WUGqnwvMQPzl** [comment]
刚才和 @xslingcn 简单讨论了下，顺便大致了解了 TurnA 的外置登录架构，在本地自行搭建了测试环境，发现 YggdrasilOfficialProxy 似乎没能正常返回玩家信息

**Comment by WUGqnwvMQPzl** [comment]
以下报错信息作为参考：
```
[22:18:21 INFO]: SpectreLake issued server command: /skull xsling
[22:18:21 INFO]: [YggdrasilOfficialProxy] [TRACE] Query profile data:
[22:18:21 INFO]:   -> Yggdrasil: [xsling]
[22:18:21 INFO]:   -> Official : [xsling]
[22:18:23 INFO]: [YggdrasilOfficialProxy] [TRACE] Query response: (officialFirst=true)
[22:18:23 INFO]:   <- Yggdrasil: []
[22:18:23 INFO]:   <- Official : [{"id":"05dcef7718e54aea8829da192b54a67e","name":"xsling"}]
> [authlib-injector] [WARNING] An error occurred while processing request [/https/sessionserver.mojang.com/session/minecraft/profile/05dcef7718e54aea8829da192b54a67e]
java.io.UncheckedIOException: java.io.FileNotFoundException: http://localhost:65534/sessionserver/session/minecraft/profile/05dcef7718e54aea8829da192b54a67e?unsigned=false
        at moe.yushi.authlibinjector.yggdrasil.YggdrasilClient.queryProfile(YggdrasilClient.java:92)
        at moe.yushi.authlibinjector.httpd.QueryProfileFilter.handle(QueryProfileFilter.java:82)
        at moe.yushi.authlibinjector.httpd.URLProcessor$1.serve(URLProcessor.java:132)
        at moe.yushi.authlibinjector.internal.fi.iki.elonen.NanoHTTPD$ClientHandler$$Lambda$4843/0x00000000e0005b80.apply(Unknown Source)
        at moe.yushi.authlibinjector.internal.fi.iki.elonen.HTTPSession.execute(HTTPSession.java:246)
        at moe.yushi.authlibinjector.internal.fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:104)
        at java.base/java.lang.Thread.run(Thread.java:836)
Caused by: java.io.FileNotFoundException: http://localhost:65534/sessionserver/session/minecraft/profile/05dcef7718e54aea8829da192b54a67e?unsigned=false
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1920)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
        at moe.yushi.authlibinjector.util.IOUtils.http(IOUtils.java:49)
        at moe.yushi.authlibinjector.yggdrasil.YggdrasilClient.queryProfile(YggdrasilClient.java:90)
        ... 6 more

[22:18:23 WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@1988ed73[id=05dcef77-18e5-4aea-8829-da192b54a67e,name=xsling,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationUnavailableException: Cannot contact authentication server
        at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:125) ~[patched_1.16.5.jar:git-Paper-780]
        at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:99) ~[patched_1.16.5.jar:git-Paper-780]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:186) ~[patched_1.16.5.jar:git-Paper-780]
        at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillGameProfile(PaperMinecraftSessionService.java:38) ~[patched_1.16.5.jar:git-Paper-780]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:179) ~[patched_1.16.5.jar:git-Paper-780]
        at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillProfileProperties(PaperMinecraftSessionService.java:31) ~[patched_1.16.5.jar:git-Paper-780]
        at net.minecraft.server.v1_16_R3.TileEntitySkull$1.load(TileEntitySkull.java:90) ~[patched_1.16.5.jar:git-Paper-780]
        at net.minecraft.server.v1_16_R3.TileEntitySkull$1.load(TileEntitySkull.java:57) ~[patched_1.16.5.jar:git-Paper-780]
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) ~[patched_1.16.5.jar:git-Paper-780]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) ~[patched_1.16.5.jar:git-Paper-780]
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) ~[patched_1.16.5.jar:git-Paper-780]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) ~[patched_1.16.5.jar:git-Paper-780]
        at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[patched_1.16.5.jar:git-Paper-780]
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) ~[patched_1.16.5.jar:git-Paper-780]
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) ~[patched_1.16.5.jar:git-Paper-780]
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153) ~[patched_1.16.5.jar:git-Paper-780]
        at net.minecraft.server.v1_16_R3.TileEntitySkull$3.call(TileEntitySkull.java:231) ~[patched_1.16.5.jar:git-Paper-780]
        at net.minecraft.server.v1_16_R3.TileEntitySkull$3.call(TileEntitySkull.java:228) ~[patched_1.16.5.jar:git-Paper-780]
        at net.minecraft.server.v1_16_R3.TileEntitySkull.b(TileEntitySkull.java:247) ~[patched_1.16.5.jar:git-Paper-780]
        at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftMetaSkull.applyToItem(CraftMetaSkull.java:104) ~[patched_1.16.5.jar:git-Paper-780]
        at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftItemStack.setItemMeta(CraftItemStack.java:535) ~[patched_1.16.5.jar:git-Paper-780]
        at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftItemStack.asNMSCopy(CraftItemStack.java:42) ~[patched_1.16.5.jar:git-Paper-780]
        at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftInventory.setItem(CraftInventory.java:100) ~[patched_1.16.5.jar:git-Paper-780]
        at com.earth2me.essentials.craftbukkit.InventoryWorkaround.addOversizedItems(InventoryWorkaround.java:176) ~[?:?]
        at com.earth2me.essentials.craftbukkit.InventoryWorkaround.addOversizedItems(InventoryWorkaround.java:114) ~[?:?]
        at com.earth2me.essentials.craftbukkit.InventoryWorkaround.addItems(InventoryWorkaround.java:106) ~[?:?]
        at com.earth2me.essentials.commands.Commandskull$1$1.run(Commandskull.java:74) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-780]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-780]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1427) ~[patched_1.16.5.jar:git-Paper-780]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-780]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342) ~[patched_1.16.5.jar:git-Paper-780]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-780]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-780]
        at net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3204/0x000000005a192870.run(Unknown Source) ~[?:?]
        at java.lang.Thread.run(Thread.java:836) [?:?]
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224) ~[patched_1.16.5.jar:git-Paper-780]
        at com.google.gson.Gson.fromJson(Gson.java:887) ~[patched_1.16.5.jar:git-Paper-780]
        at com.google.gson.Gson.fromJson(Gson.java:852) ~[patched_1.16.5.jar:git-Paper-780]
        at com.google.gson.Gson.fromJson(Gson.java:801) ~[patched_1.16.5.jar:git-Paper-780]
        at com.google.gson.Gson.fromJson(Gson.java:773) ~[patched_1.16.5.jar:git-Paper-780]
        at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:105) ~[patched_1.16.5.jar:git-Paper-780]
        ... 35 more
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385) ~[patched_1.16.5.jar:git-Paper-780]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213) ~[patched_1.16.5.jar:git-Paper-780]
        at com.google.gson.Gson.fromJson(Gson.java:887) ~[patched_1.16.5.jar:git-Paper-780]
        at com.google.gson.Gson.fromJson(Gson.java:852) ~[patched_1.16.5.jar:git-Paper-780]
        at com.google.gson.Gson.fromJson(Gson.java:801) ~[patched_1.16.5.jar:git-Paper-780]
        at com.google.gson.Gson.fromJson(Gson.java:773) ~[patched_1.16.5.jar:git-Paper-780]
        at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:105) ~[patched_1.16.5.jar:git-Paper-780]
        ... 35 more
```

YggdrasilOfficialProxy 并没有返回特别有用的信息，Proxy 配置参考如下：

```
CDN {
    enable=false
    origin=""
}
api="https://user.turna.live/api/yggdrasil"
authlib-injector="./authlib-injector-1.1.38.jar"
edited=true
official-first=true
proxy {
    # The proxy of official connecting
    official {
        type=direct
    }
    # The proxy of yggdrasil connecting
    yggdrasil {
        type=direct
    }
}
# The server binding actions.
server {
    host="127.0.0.1"
    port=65534
}
```

**Comment by WUGqnwvMQPzl** [comment]
稍微有点 Off Topic 的提示：1.17 开始头颅加载似乎会走其他线程而不是直接拦截主线程运行，在安装了 ViaFabric 的 1.17 客户端上放置这些无法正常加载的头颅后并不会造成卡顿，然而这些头颅的物品形式仍旧是史蒂夫或 Alex。

**Comment by WUGqnwvMQPzl** [comment]
在给 YggdrasilOfficialProxy 简单加上 `/sessionserver/session/minecraft/profile` 的路由后，头颅异常的问题似乎解决了，附效果图：

**正版用户**

![Screenshot_20210822_031455](https://user-images.githubusercontent.com/36147447/130332635-a672d0b8-bd0c-4662-9c06-9393598d2719.png)
![Screenshot_20210822_031517](https://user-images.githubusercontent.com/36147447/130332634-c0f503f3-6c10-4319-b6b2-b422b0d895ed.png)

**外置登录用户**

![Screenshot_20210822_031543](https://user-images.githubusercontent.com/36147447/130332633-c9a6cf19-82bd-4710-b384-0d1c3f7a6d2c.png)
![Screenshot_20210822_031553](https://user-images.githubusercontent.com/36147447/130332630-ea19f12b-a700-4063-84ce-3cc790b4dda0.png)

但是这个实现稍微有些小问题，主要还是和正版玩家撞名，或是正版和外置登录同 UUID 而出现的冲突...这种冲突比较复杂，恐怕无法处理，目前的解决方案是正版用户优先，但是一些和正版用户撞名的外置登录玩家就惨了。

YggdrasilOfficialProxy 可以在玩家名后加上 `@official` 或 `@yggdrasil` 后缀以选择性加载正版或外置登录的玩家资料，但 `/skull` 的玩家名不允许包含 `@` 符号。

**Comment by Nyaasu66** [comment]
卧草，湖湖叔叔牛逼

**Comment by WUGqnwvMQPzl** [comment]
![Screenshot_20210823_014531](https://user-images.githubusercontent.com/36147447/130364855-542a29de-27f8-4a17-bcdf-6a36e28707c3.png)

已修改的 YggdrasilOfficialProxy 已实装，就差把服务端的缓存清除就可以完全解决问题了。

patch 之后会投 pr，问题基本解决。

相关 patch：
https://gist.github.com/WUGqnwvMQPzl/9d936cd2cc1904504128acd0d8d9481b
